Numpy Basic Operations

In [36]:
import numpy as np

a = np.array([2,3,6])
a
a.dtype
b = np.array([2.36,5.59,6.62])
b
b.dtype

c  = complex(3,2)
d = complex(5,6)

z = np.array([c,d])
#k = np.array([z,a])

y = np.array([a,b])
y
y.dtype
#y.len()
za = np.array([[1,2,3],[3,4,5],[5,6,7]])
za


array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [38]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [40]:
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [41]:
op = np.array([(1,2,3),(4,5,6)] , dtype=complex)
op

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [42]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [43]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [44]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

The linspace creates an array of  9 elements within 0 and 2

In [45]:
from numpy import pi
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

linspace

In [47]:
x = np.linspace(0,2*pi,100)
f = np.sin(x)

calculating the sin values

In [69]:
y = np.linspace(0,pi/2,4)
f = np.sin(y)
#for i in y:
    #print("sin",i,np.sin([i]))
print(f)   

[0.        0.5       0.8660254 1.       ]


User Defined Functions    

In [70]:
def f(x):
    return(x**3)
print(f(y))

[0.         0.14354758 1.14838062 3.87578459]


Send Angle give the sin value

In [81]:
import numpy as np
def answer(x1):
    print(f'The sin value for {x1} is {np.sin(x1)}')
qs = input('Give an angle:')
answer(int(qs))

Give an angle:90
The sin value for 90 is 0.8939966636005579


printing arrays

In [82]:
a= np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [83]:
b = np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [85]:
c = np.arange(24).reshape(2,4,3)
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

large array

In [87]:
z = np.arange(10000)
z

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [93]:
print(np.arange(1000).reshape(5,10,20))

[[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16
    17  18  19]
  [ 20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
    37  38  39]
  [ 40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56
    57  58  59]
  [ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76
    77  78  79]
  [ 80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96
    97  98  99]
  [100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116
   117 118 119]
  [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136
   137 138 139]
  [140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156
   157 158 159]
  [160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176
   177 178 179]
  [180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196
   197 198 199]]

 [[200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216
   217 218 219]
  [220 221 222 223 224 225 226 227 228 22

In [94]:
print(np.log(1))

0.0


print all values

In [96]:
import sys
c = np.set_printoptions(threshold=sys.maxsize)

operations on arrays

axis operations

In [104]:
b = np.arange(12).reshape(3,4)
print(b)
print("\n")
print(b.sum(axis=0))
print("\n")
print(b.sum(axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[12 15 18 21]


[ 6 22 38]


Assn: Find the correlation coefficient using numpy array