Matrix Multiplication Using Numpy 

In [2]:
import numpy as np
a= [[1,2,3],[4,5,6],[7,8,9]]
b= [[1,2,3,4],[4,5,6,7],[7,8,9,10]]

c= np.matmul(a,b)
print(c)

[[ 30  36  42  48]
 [ 66  81  96 111]
 [102 126 150 174]]


Generalized Matrix Multiplication

In [11]:
a= [[1,2,3],[4,5,6],[7,8,9]]
b= [[1,2,3,4],[4,5,6,7],[7,8,9,10]]

if(len(a[0])!=len(b)):
    print("Matrix Multiplication not possible")
else:     
    c = [[0]*len(b[0]) for i in range(len(a))]
    
    for i in range(0,len(a)):
        for j in range(0,len(b[0])):
            for k in range(0,len(a[0])):
                c[i][j]+= a[i][k]*b[k][j]
    
    for i in range(0,len(c)):
        print(c[i],"\t")
   
    

[30, 36, 42, 48] 	
[66, 81, 96, 111] 	
[102, 126, 150, 174] 	


Gaussian Elimination for a Normal Square Matrix 3 by 3 without Generalization

In [7]:
A = [[1,2,3],[4,5,6],[7,8,9]]
for c in range(0,len(A)):
    print(A[c])
print("\n")    

A[1][0] = A[1][0] - (A[1][0]/A[0][0])*A[0][0]
A[2][0] = A[2][0] - (A[2][0]/A[0][0])*A[0][0]

# pivot is A[1][1]
A[2][1] = A[2][1] - (A[2][1]/A[1][1])*A[1][1]


for c in range(0,len(A)):
    print(A[c])

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


[1, 2, 3]
[0.0, 5, 6]
[0.0, 0.0, 9]


Generalized Gauss Elimination for square matrix

In [24]:
A = [[1,1,1,1],[6,-4,5,7],[5,2,2,9],[7,8,9,3]]

for k in range(0,len(A)-1):
    for i in range(k+1,len(A)):
        l = A[i][k]/A[k][k]
        for j in range(0,len(A)):
            A[i][j] = A[i][j] - l*A[k][j]

print(A)            
      
    

[[1, 1, 1, 1], [0.0, -10.0, -1.0, 1.0], [0.0, 0.0, -2.7, 3.7], [0.0, 0.0, 0.0, -1.2962962962962963]]


Determinant of a Matrix , First we use Gauss Elimination and then take product of the elements in the diagonal

In [29]:
det = 1
for i in range(0,len(A)):
    det *=A[i][i]
print("The determinant of the matrix A is :",det)    

The determinant of the matrix A is : -35.0
